name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Generate Snake
      uses: Platane/snk@v3
      id: snake-gif
      with:
        github_user_name: tirohan
        outputs: |
          dist/snake.svg
          dist/snake-dark.svg?palette=github-dark
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Show build status
      run: git status
      
    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update snake contributions
